#!/usr/bin/expect -f

set timeout -1
set ip "49.13.237.226"
set old_password "qhgrenccgqgh3xiPPNF9"
set new_password "Sanskrit_Ruhrpott_2025!"

spawn ssh -o StrictHostKeyChecking=no root@$ip
expect {
    "password:" { send "$old_password\r" }
}

expect {
    "Current password:" { send "$old_password\r" }
    "password:" { send "$old_password\r" }
}

expect "New password:"
send "$new_password\r"

expect "Retype new password:"
send "$new_password\r"

expect "#"
send "exit\r"
expect eof
